name: Build LaTeX document
on: 
  push:
  workflow_dispatch:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      
      - name: Compile book
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: book
      
      - name: Compile paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: research_paper
      
      - name: Collect PDFs
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: */*.pdf