name: Build LaTeX document
on: 
  push:
  workflow_dispatch:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile book and paper
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: cp .latexmkrc $HOME/.latexmkrc
          work_in_root_file_dir: true
          root_file: |
            book/main.tex
            research_paper/main.tex
      
      - name: Collect PDFs
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: |
            */*.pdf